spring:
  security:
    oauth2.client:
      registration:
        google:
          clientId: 318085017753-mr69j8f3n5tg64rjqalfjm0j1elkvk5j.apps.googleusercontent.com #본인꺼등록
          clientSecret: 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     #본인꺼등록
          scope: email,profile

          # 네이버는 Spring Security를 공식 지원하지 않기 때문에 Provider 값들을 수동으로 입력한다.
        naver:
          client-id: D8GF7CAScZjuKgZjuFGE #본인꺼등록
          client-secret:  NgP1XM08GO  #본인꺼등록
          redirect-uri: "http://localhost:8099/login/oauth2/code/naver"
          authorization-grant-type: authorization_code
          scope:
            - email
            - nickname
          client-name: Naver
        kakao:
          client-id: 8d1bfff0893723a74b9b690f2047a0f1   #본인꺼등록
          redirect-uri: "http://localhost:8099/login/oauth2/code/kakao"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: profile_nickname, account_email #동의 항목
          client-name: Kakao

  #이렇게 꼭 써야한다
      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id


#  http://localhost:8099/login/oauth2/code/kakao